name: Linux
on:
  push:
    branches: [master]

env:
  ovito_version: 3.15.4

jobs:
  LinuxOvito:
    runs-on: ubuntu-latest
    
    steps:
      - name: Requirements
        run: |
          sudo apt-get update 
          sudo apt-get install build-essential git cmake-curses-gui qt6-base-dev libqt6svg6-dev \
          libboost-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev \
          libavutil-dev libswscale-dev libnetcdf-dev libhdf5-dev libhdf5-serial-dev \
          libglu1-mesa-dev ninja-build libssh-dev python3-sphinx python3-sphinx-rtd-theme

      - name: Build
        run: |
          git clone --recursive https://gitlab.com/stuko/ovito.git 
          cd ovito && git checkout v${{env.ovito_version}} && mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../Install 
          ninja install -j4
      

