name: Use Docker Image in CI
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Pull and run
        run: |
          docker pull registry.gitlab.com/stuko/ovito/linux_build:latest
          docker run --rm registry.gitlab.com/stuko/ovito/linux_build:latest bash -c "
            apt-get update && \
            apt-get install -y gromacs && \
            gmx --version
          "
