name: Build Windows x64 latest Ovito Basic without CUDA render

on:
  push:
    branches:
      - master

env:
  ovito_version: "3.15.3"
  ffpmeg_version: "ffmpeg-7.1-full_build-shared"
  qt_version: 6.8.3
  PYTHONHOME: "C:/hostedtoolcache/windows/Python/3.12.10/x64" 

jobs:
  Windows:
    runs-on: windows-2022
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Setup vcpkg binary cache
        run: |
            dir ${{env.PYTHONHOME}}
            dir ${{env.PYTHONHOME}}\..
            echo "VCPKG_BINARY_SOURCES=clear;x-gha,readwrite" >> $GITHUB_ENV

      - name: Download dependencies
        run: |
          vcpkg install hdf5 netcdf-c libssh --triplet x64-windows-release --binarysource="clear;x-gha,readwrite"
          ls C:/vcpkg/packages
          ls C:/vcpkg/packages/hdf5_x64-windows-release/bin

      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
