name: Build Windows x64 latest Ovito Basic without CUDA render

on:
  push:
    branches:
      - master

env:
  ovito_version: "3.15.3"
  ffpmeg_version: "ffmpeg-7.1-full_build-shared"
  qt_version: 6.8.3
  PYTHONHOME: "C:/hostedtoolcache/windows/Python/3.12.10/x64" 

jobs:
  Windows:
    runs-on: windows-2022
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Setup vcpkg binary cache
        run: echo "VCPKG_BINARY_SOURCES=clear;x-gha,readwrite" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10' 
        
      - name: Download Ovito source code
        shell: bash
        run: |
            rm -rf "C:/Android/android-sdk" "C:/hostedtoolcache/windows/Python/3.14.5"
            #curl -O https://gitlab.com/stuko/ovito/-/archive/v${{env.ovito_version}}/ovito-v${{env.ovito_version}}.tar.gz
            #tar -xf ovito-v${{env.ovito_version}}.tar.gz

            ## use git for external zstd, get ovito folder
            #git clone --branch dev${{env.ovito_version}} --recursive https://gitlab.com/stuko/ovito.git

            # m-ovito to 3.15.0
            git clone --recursive https://github.com/blualg/m-ovito.git
            cd m-ovito
            git checkout main
            git submodule update --init --recursive
            # delete noexist .cpp
            sed -i '98,280d' src/main/CMakeLists.txt
            cd ..
            mv m-ovito ovito-v${{env.ovito_version}}
            
            #fix zlib1 name
            # sed -i 's/zlib\.dll/z.dll/g' ovito-v${{env.ovito_version}}/src/ovito/core/CMakeLists.txt
            # download win64 for manual
            curl -O https://www.ovito.org/download/master/ovito-basic-${{env.ovito_version}}-win64.zip
            unzip ovito-basic-${{env.ovito_version}}-win64.zip -d win64_temp
            rm -rf ovito-basic-${{env.ovito_version}}-win64.zip

      - name: Install boost
        uses: MarkusJx/install-boost@v2.6.0
        id: boost
        with:
            boost_version: 1.88.0
            platform_version: 2022
            # install to C:\boost
            boost_install_dir: C:\

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4.3.1
        with:
          version: ${{env.qt_version}}
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          dir: C:\Qt6
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          archives: 'qtbase qtsvg'
          cache: 'false'
          cache-key-prefix: 'install-qt-action'

      - name: Install ffmpeg
        run: |
          choco install p7zip wget
          #wget https://www.gyan.dev/ffmpeg/builds/packages/${{env.ffpmeg_version}}.7z
          wget https://github.com/GyanD/codexffmpeg/releases/download/7.1/${{env.ffpmeg_version}}.7z
          7z x ${{env.ffpmeg_version}}.7z
          Copy-Item -Path ${{env.ffpmeg_version}}\bin\*.dll ${{env.ffpmeg_version}}\lib\
          Move-Item -Path ${{env.ffpmeg_version}} -Destination C:\
          Remove-Item -Path ${{env.ffpmeg_version}}.7z

      - name: Download dependencies
        run: |
          vcpkg install hdf5 netcdf-c libssh --triplet x64-windows-release
          ls C:/vcpkg/packages
          ls C:/vcpkg/packages/hdf5_x64-windows-release/bin

